import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex flex-col md:flex-row bg-white h-screen">
      {/* বাম পাশের ফিক্সড সাইডবার */}
      <Sidebar />

      {/* ডান পাশের ডাইনামিক কন্টেন্ট এরিয়া */}
      <main className="flex-1   flex justify-center  md:justify-end">
        <div className="bg-white min-w-[95%] md:min-w-[70%] min-h-[calc(100vh-64px)] ">{children}</div>
      </main>
    </div>
  );
}
